# These are supported funding model platforms

github: [SergiX44]
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
ko_fi: #
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
custom: http://bit.ly/XBackBonePaypal
